### ISSUE TITLE
linker command failed with exit code 1 ?

### ISSUE THREAD

**Issue by fadylateef** [ChaosTong/SwiftFFmpegPlayer#1]
Hello, 
First thanks for great library .
I tried to build your project but it gives me an error 
```
  "_av_dump_format", referenced from:
      cPlayer.VideoDecoder.openFile(Swift.String?) -> Swift.Bool in VideoDecoder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ChaosTong** [comment]
seems like i build the ffmpeg-ios lib do not include x86 file for simulator, you can try to use real phone or use this repo
https://github.com/kewlbear/FFmpeg-iOS-build-script to build one can support iOS simulator
